[package]
name = "pluto_engine_display"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pluto_engine_window = { path = "../window" }
pluto_engine_render = { path = "../render" }